### ISSUE TITLE
Зачем отсекать часы?

### ISSUE THREAD

**Issue by niello** [AndreyGovnocoder/SoundAround_2.0#11]
https://github.com/AndreyGovnocoder/SoundAround_2.0/blob/8eeea14f97d0462e90d5c5be3191dc3b41b91c66/Helper.cpp#L77

Здесь если запись длится 30 часов, то будет написано, что 6, потому что все целые сутки ты отрезаешь. Это точно так и задумано?

**Comment by AndreyGovnocoder** [comment]
вот честно, я прям сам удивлён зачем я так сделал, а главное что именно я хотел этим сделать О_О 
вообще не помню, может попутал с чем... короче убрал эту строку
