### ISSUE TITLE
Похоже на код из хелпера

### ISSUE THREAD

**Issue by niello** [AndreyGovnocoder/SoundAround_2.0#15]
https://github.com/AndreyGovnocoder/SoundAround_2.0/blob/8eeea14f97d0462e90d5c5be3191dc3b41b91c66/TrackFrame.cpp#L353-L357

https://github.com/AndreyGovnocoder/SoundAround_2.0/blob/8eeea14f97d0462e90d5c5be3191dc3b41b91c66/Track.cpp#L23-L27

Там точно было или точно такое же, или очень похожее. Не получится реюзнуть оттуда функции?

**Comment by AndreyGovnocoder** [comment]
тут немного отличается, в хэлпере все удаляется, ищется или возвращается из общего списка, а в этих двух - из списка конкретного трека. но я все равно чуть исправил, хз лучше или нет

**Comment by niello** [comment]
find вместо find_if в этом случае точно лучше. Так же можно использовать remove вместо remove_if, это всегда работает, когда ты прям готовое значение из массива указываешь.
