### ISSUE TITLE
Лишнее переключение на невалидную запись в запросе

### ISSUE THREAD

**Issue by niello** [AndreyGovnocoder/SoundAround_2.0#4]
https://github.com/AndreyGovnocoder/SoundAround_2.0/blob/8eeea14f97d0462e90d5c5be3191dc3b41b91c66/Database.cpp#L89-L90

Насколько я понял из документации к QSqlQuery, можно выполнить его, а потом просто делать query.next() в цикле. И первый вызов next поставит курсор на первую строку сам: https://doc.qt.io/qt-5/qsqlquery.html#next

**Comment by AndreyGovnocoder** [comment]
тут не совсем тебя понял. 
я делаю запрос, перемещаю курсор на последнюю запись что бы получить количество строк что бы зарезервировать место в векторе, и если после этого не делать  query.first();  query.previous();  то при query.next() перебор начинается с того места где стоит курсор, и в итоге в вектор ничего не добавляется. поэтому приходится ставить курсор на first() (но тогда он начинает перебор именно с 1ой записи, а нулевую пропускает) и затем ставить курсор на предыдущую. я еще когда это делал давно в orderbase подумал что как то глупо получается, но ты тогда ничего не сказал, вот и подумал что так норм)))
сейчас я сделал что выполняется два раза запрос, тут мне кажется тоже неправильно, но я так и не смог придумать ничего другого, либо резервировать место в векторе и делать два запроса, либо не резервировать место в вектора и делать один запрос, либо оставить это перемещение курсора

**Comment by niello** [comment]
Тогда оставить перемещение курсора будет самым правильным. Я не учёл, что для получения количества записей надо перемотаться на конец.
